### PR TITLE
WIP: exemplary annotation of three MSI datasets

### PR DESCRIPTION
**Pull request by foellmelanie**
this is hopefully a starting point to discuss how MSI datasets can be represented in the format

### CODE REVIEW

**Comment by foellmelanie** [comment]
mh...comment[cleavage agent details] is mandatory but does not accept "not applicable", how could this be solved?

**Comment by foellmelanie** [comment]
The latest Bruker instruments (rapifleX, timsTOF fleX) used for MSI are not available in the ontology: 
https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000031&viewMode=All&siblings=false

**Comment by ypriverol** [comment]
@foellmelanie can you change the PR add some of the ideas in the #451 into the specification. I mean, would be really nice to review the example, plus the specification in the PR to have both updated.

**Comment by ypriverol** [comment]
@foellmelanie I have created an issue #454 to make the `not applicable` the enzyme. When you make the modifications to the specification can you add a sentence to https://github.com/bigbio/proteomics-metadata-standard/tree/master/sample-metadata#42-enzyme section to make clear that is possible. We are modifying the validator accordingly.

**Comment by ypriverol** [comment]
PR https://github.com/HUPO-PSI/psi-ms-CV/pull/45 added the rapiplex

**Comment by foellmelanie** [comment]
Thanks @ypriverol for adding rapiflex. Could you please also add the newest one [timsTOF fleX](https://www.bruker.com/products/mass-spectrometry-and-separations/lc-ms/o-tof/timstof-flex.html)

**Comment by ypriverol** [comment]
@foellmelanie instrument here https://github.com/HUPO-PSI/psi-ms-CV/pull/46

**Comment by ypriverol** [comment]
@foellmelanie I will close this PR. We can try to recover it if we get more attention in the future.

**Pull request closed without merging**
