### PR TITLE
added sdrf from xroulab samplesheets

### PR DESCRIPTION
**Pull request by NicolasProvencher**
Added 141 sdrf from samplessheet of manually curated pride studies 

Unsure if the correct use of TMT label since our curation was made per file instead of per sample thus making all tmt asscosiated to tmt6plex through comment modification column

### CODE REVIEW

**Comment by ypriverol** [comment]
@NicolasProvencher it will take is sometime to review the datasets. Impressive contribution, if you find in the meantime some info about the TMT would be amazing.

**Comment by NicolasProvencher** [comment]
seems like your validation tools pulled up some problems that the one i used didnt i will get right on fixing those

**Comment by ypriverol** [comment]
@NicolasProvencher some of the experiments are linking to mgf files and not have any information about the label, not the correct label. I suggest that in the name of those files you put like {PX Accession}-identification.sdtf.tsv to make clear to users of these SDRF that they can be used mainly for peptide/protein identification, but they have missing data needed for quant. What do you think?

**Comment by ypriverol** [comment]
@NicolasProvencher any update on this?

**Comment by NicolasProvencher** [comment]
This isnt a priority for us right now, ill cancel the merge for now and redo it once we have time to manually go back through all the study to add the missing info

**Comment by ypriverol** [comment]
Thanks, I will close the PR for now.

**Pull request closed without merging**
