### PR TITLE
Create PXD026474

### PR DESCRIPTION
**Pull request by omcamacho**

### CODE REVIEW

**Review by ypriverol — CHANGES_REQUESTED** [review]
I don't see any file added to the folder I was expecting to see here, something like a `PXD026474.sdrf.tsv`

**Comment by omcamacho** [comment]
I thought first the folder was created and then I would add the file Best regards,Óscar On 27 Oct 2023, at 15:02, Yasset Perez-Riverol ***@***.***> wrote:﻿
@ypriverol requested changes on this pull request.

I don't see any file added to the folder I was expecting to see here, something like a PXD026474.sdrf.tsv

**Comment by omcamacho** [comment]
Could you reject and I'll try again please. Thanks
    En viernes, 27 de octubre de 2023, 14:02:29 GMT+1, Yasset Perez-Riverol ***@***.***> escribió:  
 
 


@ypriverol requested changes on this pull request.

I don't see any file added to the folder I was expecting to see here, something like a PXD026474.sdrf.tsv

**Comment by omcamacho** [comment]
Incorrect request

**Pull request closed without merging**
