### PR TITLE
Definition of Data acquisition method in the specification [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by ypriverol**
This PR includes small changes in the specification to define how DIA experiments and other acquisition methods. In addition, an example and other small fixes are done in other datasets.

### CODE REVIEW

**Review by nithujohn — APPROVED** [review]

**Review by daichengxin — APPROVED** [review]

**Review by nithujohn — APPROVED** [review]

**Comment by trishorts** [comment]
This is good stuff. Really appreciate your service to the community. Maybe there is stuff in another place that I am not aware of.

But, I wonder where the info about which protease (if any) is located. Also wonder about what search engine and version and parameters is located. Also, what about the datails of the protein database (fasta or xml). 

Can you point me to the definitions file for each of your headings? I don't know what you expect for modifications, etc.

**Comment by ypriverol** [comment]
> This is good stuff. Really appreciate your service to the community. Maybe there is stuff in another place that I am not aware of.
> 
> But, I wonder where the info about which protease (if any) is located. 

https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/README.adoc#1022-cleavage-agents

Also wonder about what search engine and version and parameters is located. Also, what about the datails of the protein database (fasta or xml).

We are trying to do not encode databases because it can change from experiment to reanalyses. 

> 
> Can you point me to the definitions file for each of your headings? I don't know what you expect for modifications, etc.

Some data analysis fields https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/data-analysis-metadata.adoc

**Comment by trishorts** [comment]
so wonder about what search engine and version and parameters is located. Also, what about the datails of the protein database (fasta or xml).
> 
> We are trying to do not encode databases because it can change from experiment to reanalyses.
>

Nonetheless, with knowledge of the protein sequence data that was used, it becomes hard to reproduce the original result. Re-analysis is important. But, I think reproduction is equally important. So, metadata should store everything necessary to enable reproduction. You don't have to store the FASTA/XML. But, one should know the location and date when it was obtained and if modifications were obtained there. 

This is opinion of course.

**Comment by ypriverol** [comment]
> so wonder about what search engine and version and parameters is located. Also, what about the datails of the protein database (fasta or xml).
> 
> > We are trying to do not encode databases because it can change from experiment to reanalyses.
> 
> Nonetheless, with knowledge of the protein sequence data that was used, it becomes hard to reproduce the original result. Re-analysis is important. But, I think reproduction is equally important. So, metadata should store everything necessary to enable reproduction. You don't have to store the FASTA/XML. But, one should know the location and date when it was obtained and if modifications were obtained there.
> 
> Similarly, all the search software metadata should come along. Engine, version and all settings.
> 
> This is opinion of course.

I think for search engines and data analysis we should continue the work started by @david-bouyssie @veitveit https://github.com/bigbio/proteomics-sample-metadata/blob/master/sdrf-proteomics/data-analysis-metadata.adoc which are still not part of the full specification but a proposal about how to capture these fields. 

This PR is mainly to discuss how in the current specification we can capture DDA vs DIA which is getting requested more and more by users. It would be great from your point of view to see what other parameters we should capture in DIA instrument settings.

**Review by nithujohn — APPROVED** [review]

**Review by enryH — APPROVED** [review]

**Review by TineClaeys — APPROVED** [review]

**Comment by ypriverol** [comment]
This PR adds the terms needed for this PR https://github.com/PRIDE-Utilities/pride-ontology/pull/104

**Pull request merged**
